name: Build and Publish Docker

on:
  push:
    branches:
      - master

jobs:
  build_4_0_0:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        BUILD_DATE: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
        VCS_URL: $(git config --get remote.origin.url)
        VCS_REF: $(git rev-parse --short HEAD)
        GCC_VERSION: 9.2.0
        OMPI_VERSION: 4.0.0
        EXTRA_SPECS: "target=skylake"
      with:
        name: leavesask/gompi
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildargs: GCC_VERSION,OMPI_VERSION,EXTRA_SPECS,BUILD_DATE,VCS_URL,VCS_REF
        buildoptions: "--compress"
        tags: "latest,4.0.0,4.0.0-gcc-9.2.0"

  build_3_1_5:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        BUILD_DATE: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
        VCS_URL: $(git config --get remote.origin.url)
        VCS_REF: $(git rev-parse --short HEAD)
        GCC_VERSION: 9.2.0
        OMPI_VERSION: 3.1.5
        EXTRA_SPECS: "target=skylake"
      with:
        name: leavesask/gompi
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildargs: GCC_VERSION,OMPI_VERSION,EXTRA_SPECS,BUILD_DATE,VCS_URL,VCS_REF
        buildoptions: "--compress"
        tags: "3.1.5,3.1.5-gcc-9.2.0"
